spring:
  application:
    name: paymentApi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa?serverTimezone=Asia/Seoul
    username: root
    password: admin
  jpa:
    show-sql: true

server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
