server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userApi
          uri: lb://USERAPI
          predicates:
            - Path=/api/users/**
        - id: productApi
          uri: lb://PRODUCTAPI
          predicates:
            - Path=/api/products/**
        - id: accountApi
          uri: lb://ACCOUNTAPI
          predicates:
            - Path=/api/accounts/**
        - id: paymentApi
          uri: lb://PAYMENTAPI
          predicates:
            - Path=/api/payments/**
